(function(e){e.formValidator={initConfig:function(d){var a={};e.extend(!0,a,initConfig_setting,d||{});if(a.mode=="SingleTip")a.errorFocus=!1;a.formID!=""&&e("#"+a.formID).submit(function(){return a.ajaxForm!=null?(e.formValidator.ajaxForm(a.validatorGroup,a.ajaxForm),!1):e.formValidator.bindSubmit(a)});validatorGroup_setting.push(a);d=fv_scriptSrc.split("/");d=fv_scriptSrc.replace(d[d.length-1],"");e.ajax({async:!1,type:"GET",url:d+"themes/"+a.theme+"/js/theme.js",dataType:"script",error:function(){alert("\u5f53\u524d\u76ae\u80a4\u52a0\u8f7d\u51fa\u9519\uff0c\u8bf7\u786e\u8ba4\u76ae\u80a4\u3010"+
a.theme+"\u3011\u662f\u5426\u5b58\u5728")}});if(e.browser.msie){var c=document.createElement("link");c.rel="stylesheet";c.type="text/css";c.href=d+"themes/"+a.theme+"/style/style.css"}else c=document.createElement("style"),c.setAttribute("type","text/css"),d="@import url('"+d+"themes/"+a.theme+"/style/style.css');",c.styleSheet?c.styleSheet.cssText=d:c.appendChild(document.createTextNode(d));document.getElementsByTagName("head")[0].appendChild(c)},bindSubmit:function(d){if(d.ajaxCountValid>0&&d.ajaxPrompt!=
"")return alert(d.ajaxPrompt),!1;return e.formValidator.pageIsValid(d.validatorGroup)},sustainType:function(d,a){var c=d.tagName,e=d.type;switch(a){case "formValidator":return!0;case "inputValidator":return c=="INPUT"||c=="TEXTAREA"||c=="SELECT";case "compareValidator":return c=="INPUT"||c=="TEXTAREA"?e!="checkbox"&&e!="radio":!1;case "ajaxValidator":return e=="text"||e=="textarea"||e=="file"||e=="password"||e=="select-one";case "regexValidator":return c=="INPUT"||c=="TEXTAREA"?e!="checkbox"&&e!=
"radio":!1;case "functionValidator":return!0;case "passwordValidator":return e=="password"}},appendValid:function(d,a){var c=e("#"+d).get(0),f=a.validateType;if(!e.formValidator.sustainType(c,f))return-1;if(f=="formValidator"||c.settings==void 0)c.settings=[];f=c.settings.push(a);c.settings[f-1].index=f-1;return f-1},getInitConfig:function(d){var a=null;e.each(validatorGroup_setting,function(c){if(validatorGroup_setting[c].validatorGroup==d)return a=validatorGroup_setting[c],!1});return a},setTipState:function(d,
a,c){var f=e.formValidator.getInitConfig(d.validatorGroup),g=e("#"+d.settings[0].tipID);if(c==null||c=="")g.hide();else if(f.mode=="SingleTip")e("#fv_content").html(c),d.Tooltip=c,a!="onError"&&g.hide();else{f=a=="onShow"?onShowHtml:a=="onFocus"?onFocusHtml:a=="onCorrect"?onCorrectHtml:onErrorHtml;if(f.length=c=="")g.hide();else{if(d.validatorPasswordIndex>0&&a=="onCorrect"){var h=d.settings[d.validatorPasswordIndex],i=e.formValidator.passwordValid(d),c="";if(i==-1&&h.onErrorContinueChar!="")c=h.onErrorContinueChar;
else if(i==-2&&h.onErrorSameChar!="")c=h.onErrorSameChar;else if(i==-3&&h.onErrorCompareSame!="")c=h.onErrorCompareSame;if(c!=""){e.formValidator.setTipState(d,"onError",c);return}c=passwordStrengthText[i<=0?0:i-1]}f=f.replace(/\$class\$/g,a).replace(/\$data\$/g,c);g.html(f).show()}c=d.type;if(c=="password"||c=="text"||c=="file")jqobj=e(d),onShowClass!=""&&a=="onShow"&&jqobj.removeClass().addClass(onShowClass),onFocusClass!=""&&a=="onFocus"&&jqobj.removeClass().addClass(onFocusClass),onCorrectClass!=
""&&a=="onCorrect"&&jqobj.removeClass().addClass(onCorrectClass),onErrorClass!=""&&a=="onError"&&jqobj.removeClass().addClass(onErrorClass)}},resetTipState:function(d){d==void 0&&(d="1");d=e.formValidator.getInitConfig(d);e.each(d.validObjects,function(){var a=this.settings[0],c=a.defaultPassed;e.formValidator.setTipState(this,c?"onCorrect":"onShow",c?e.formValidator.getStatusText(this,a.onCorrect):a.onShow)})},setFailState:function(d,a){e.formValidator.setTipState(e("#"+d).get(0),"onError",a)},showMessage:function(d){var a=
d.id,c=e("#"+a).get(0),f=d.isValid,g=d.setting,h="",i="",j=e.formValidator.getInitConfig(c.validatorGroup);f?(h=e.formValidator.isEmpty(a)?g.onEmpty:e.formValidator.getStatusText(c,g.onCorrect),e.formValidator.setTipState(c,"onCorrect",h)):(i="onError",g.validateType=="ajaxValidator"?g.lastValid==""?(i="onLoad",h=g.onWait):h=e.formValidator.getStatusText(c,g.onError):h=d.errormsg==""?e.formValidator.getStatusText(c,g.onError):d.errormsg,j.mode=="AlertTip"?c.validValueOld!=e(c).val()&&alert(h):e.formValidator.setTipState(c,
i,h));return h},showAjaxMessage:function(d){var a=e("#"+d.id).get(0),c=a.settings[d.ajax],f=a.validValueOld,g=e(a).val();d.setting=c;if(f!=g||f==g&&a.onceValided==void 0)e.formValidator.ajaxValid(d);else{if(c.isValid!=void 0&&!c.isValid)a.lastshowclass="onError",a.lastshowmsg=e.formValidator.getStatusText(a,c.onError);e.formValidator.setTipState(a,a.lastshowclass,a.lastshowmsg)}},getLength:function(d){var a=e("#"+d),c=a.get(0),f=c.type,d=0;switch(f){case "text":case "hidden":case "password":case "textarea":case "file":a=
a.val();f=c.settings[0];c.isInputControl&&c.value==f.onShowText&&(a="");if(e.formValidator.getInitConfig(c.validatorGroup).wideWord)for(c=0;c<a.length;c++)d+=a.charCodeAt(c)>=19968&&a.charCodeAt(c)<=40869?2:1;else d=a.length;break;case "checkbox":case "radio":d=e("input[type='"+f+"'][name='"+a.attr("name")+"']:checked").length;break;case "select-one":d=c.options?c.options.selectedIndex:-1;break;case "select-multiple":d=e("select[name="+c.name+"] option:selected").length}return d},isEmpty:function(d){return e("#"+
d).get(0).settings[0].empty&&e.formValidator.getLength(d)==0},isOneValid:function(d){return e.formValidator.oneIsValid(d).isValid},oneIsValid:function(d){var a={},c=e("#"+d).get(0),f=e.formValidator.getInitConfig(c.validatorGroup);a.initConfig=f;a.id=d;a.ajax=-1;a.errormsg="";var g=c.settings,h=g.length,i;if(h==1)g[0].bind=!1;if(!g[0].bind)return null;e.formValidator.resetInputValue(!0,f,d);for(var j=0;j<h;j++)if(j==0){if(e.formValidator.isEmpty(d)){a.isValid=!0;a.setting=g[0];break}}else{a.setting=
g[j];i=g[j].validateType;switch(i){case "inputValidator":e.formValidator.inputValid(a);break;case "compareValidator":e.formValidator.compareValid(a);break;case "regexValidator":e.formValidator.regexValid(a);break;case "functionValidator":e.formValidator.functionValid(a);break;case "ajaxValidator":a.ajax=j}c.onceValided=!0;if(g[j].isValid){if(a.isValid=!0,a.setting=g[0],g[j].validateType=="ajaxValidator")break}else{a.isValid=!1;a.setting=g[j];break}}e.formValidator.resetInputValue(!1,f,d);return a},
pageIsValid:function(d){d==void 0&&(d="1");var a=!0,c,f="",g,h="^",i,j,l="^",m=[],k=e.formValidator.getInitConfig(d);k.status="sumbiting";k.ajaxCountSubmit=0;e.each(k.validObjects,function(){if(e(this).length==0)return!0;if(this.settings[0].bind&&this.validatorAjaxIndex!=void 0&&this.onceValided==void 0&&(c=e.formValidator.oneIsValid(this.id),c.ajax==this.validatorAjaxIndex))k.status="sumbitingWithAjax",e.formValidator.ajaxValid(c)});if(k.ajaxCountSubmit>0)return!1;e.each(k.validObjects,function(){if(e(this).length==
0)return!0;if(this.settings[0].bind&&(j=this.name,l.indexOf("^"+j+"^")==-1&&(onceValided=this.onceValided==void 0?!1:this.onceValided,j&&(l=l+j+"^"),c=e.formValidator.oneIsValid(this.id)))){if(!c.isValid){a=!1;g=c.errormsg==""?c.setting.onError:c.errormsg;m[m.length]=g;if(i==null)i=c.id;f==""&&(f=g)}if(k.mode!="AlertTip"){var d=this.settings[0].tipID;h.indexOf("^"+d+"^")==-1&&(c.isValid||(h=h+d+"^"),e.formValidator.showMessage(c))}}});if(a){if(!k.onSuccess())return!1;k.submitOnce&&e(":submit,:button,:reset").attr("disabled",
!0)}else k.onError(f,e("#"+i).get(0),m),i&&k.errorFocus&&e("#"+i).focus();k.status="init";a&&k.debug&&alert("\u73b0\u5728\u6b63\u5904\u4e8e\u8c03\u8bd5\u6a21\u5f0f(debug:true)\uff0c\u4e0d\u80fd\u63d0\u4ea4");return!k.debug&&a},ajaxForm:function(d,a,c){d==void 0&&(d="1");var f={};e.extend(!0,f,ajaxForm_setting,a||{});a=e.formValidator.getInitConfig(d);if(c==void 0&&(c=a.formID,c==""))return alert("\u8868\u5355ID\u672a\u4f20\u5165"),!1;if(!e.formValidator.pageIsValid(d))return!1;d=f.url;c=e.formValidator.serialize("#"+
c);d+=d.indexOf("?")>-1?"&"+c:"?"+c;alert(d);e.ajax({type:f.type,url:d,cache:f.cache,data:f.data,async:f.async,timeout:f.timeout,dataType:f.dataType,beforeSend:function(c,e){f.buttons&&f.buttons.length>0&&f.buttons.attr({disabled:!0});return f.beforeSend(c,e)},success:function(c,e,a){f.success(c,e,a)},complete:function(c,e){f.buttons&&f.buttons.length>0&&f.buttons.attr({disabled:!1});f.complete(c,e)},error:function(c,e,a){f.error(c,e,a)}})},serialize:function(d,a){a!=void 0&&e.formValidator.resetInputValue(!0,
a);var c=e(d).serialize();a!=void 0&&e.formValidator.resetInputValue(!1,a);var c=c.split("&"),f="";e.each(c,function(c,e){var a=e.indexOf("=");if(a>0){var d=e.substring(0,a),a=escape(decodeURIComponent(e.substr(a+1))),d=d+"="+a;f=f==""?d:f+"&"+d}});return f},ajaxValid:function(d){var a=d.id,c=e("#"+a).get(0),f=d.initConfig,g=c.settings,h=g[d.ajax],i=h.url,j=c.validatorGroup,f=e.formValidator.getInitConfig(j),l=e.formValidator.serialize(f.ajaxObjects),l="clientid="+a+"&"+(h.randNumberName?h.randNumberName+
"="+((new Date).getTime()+Math.round(Math.random()*1E4)):"")+(l.length>0?"&"+l:"");i+=i.indexOf("?")>-1?"&"+l:"?"+l;e.ajax({type:h.type,url:i,cache:h.cache,data:h.data,async:h.async,timeout:h.timeout,dataType:h.dataType,success:function(a,k,i){var n=!1;e.formValidator.dealAjaxRequestCount(j,-1);k=h.success(a,k,i);typeof k=="string"?a="onError":k?(n=!0,a="onCorrect",k=g[0].onCorrect):(a="onError",k=e.formValidator.getStatusText(c,h.onError),alert(k));h.isValid=n;e.formValidator.setTipState(c,a,k);
d.initConfig.status=="sumbitingWithAjax"&&d.initConfig.ajaxCountSubmit==0&&f.formID!=""&&e("#"+f.formID).trigger("submit")},complete:function(a,e){h.buttons&&h.buttons.length>0&&h.buttons.attr({disabled:!1});h.complete(a,e)},beforeSend:function(a,f){this.lastXMLHttpRequest&&this.lastXMLHttpRequest.abort();this.lastXMLHttpRequest=a;h.buttons&&h.buttons.length>0&&h.buttons.attr({disabled:!0});var i=h.beforeSend(a,f),n=!1;h.isValid=!1;typeof i=="boolean"&&i?(n=!0,e.formValidator.setTipState(c,"onLoad",
g[d.ajax].onWait)):(n=!1,e.formValidator.setTipState(c,"onError",i));h.lastValid="-1";n&&e.formValidator.dealAjaxRequestCount(j,1);return n},error:function(a,d,f){e.formValidator.dealAjaxRequestCount(j,-1);e.formValidator.setTipState(c,"onError",e.formValidator.getStatusText(c,h.onError));h.isValid=!1;h.error(a,d,f)},processData:h.processData})},dealAjaxRequestCount:function(d,a){var c=e.formValidator.getInitConfig(d);c.ajaxCountValid+=a;c.status=="sumbitingWithAjax"&&(c.ajaxCountSubmit+=a)},regexValid:function(d){var a=
d.id,c=d.setting;e("#"+a).get(0);var f=e("#"+a).get(0),g;if(f.settings[0].empty&&f.value=="")c.isValid=!0;else if(d=c.regExp,c.isValid=!1,typeof d=="string"&&(d=[d]),e.each(d,function(){var a=this;c.dataType=="enum"&&(a=eval("regexEnum."+a));if(a==void 0||a=="")return!1;g=RegExp(a,c.param).test(e(f).val());if(c.compareType=="||"&&g)return c.isValid=!0,!1;if(c.compareType=="&&"&&!g)return!1}),!c.isValid)c.isValid=g},functionValid:function(d){var a=d.setting,c=e("#"+d.id),c=a.fun(c.val(),c.get(0));
c!=void 0?typeof c==="string"?(a.isValid=!1,d.errormsg=c):a.isValid=c:a.isValid=!0},inputValid:function(d){var a=d.id,c=d.setting,f=e("#"+a),g=f.get(0),f=f.val(),g=g.type,a=e.formValidator.getLength(a),h=c.empty,i=!1;switch(g){case "text":case "hidden":case "password":case "textarea":case "file":if(c.type=="size"&&(h=c.empty,h.leftEmpty||(i=f.replace(/^[ \s]+/,"").length!=f.length),!i&&!h.rightEmpty&&(i=f.replace(/[ \s]+$/,"").length!=f.length),i&&h.emptyError))d.errormsg=h.emptyError;case "checkbox":case "select-one":case "select-multiple":case "radio":h=
!1;if(g=="select-one"||g=="select-multiple")c.type="size";g=c.type;if(g=="size")i||(h=!0),h&&(f=a);else if(g=="date"||g=="datetime"){if(g=="date"&&(h=isDate(f)),g=="datetime"&&(h=isDate(f)),h)f=new Date(f),c.min=new Date(c.min),c.max=new Date(c.max)}else stype=typeof c.min,stype=="number"&&(f=(new Number(f)).valueOf(),isNaN(f)||(h=!0)),stype=="string"&&(h=!0);c.isValid=!1;if(h)if(f<c.min||f>c.max){if(f<c.min&&c.onErrorMin)d.errormsg=c.onErrorMin;if(f>c.min&&c.onErrorMax)d.errormsg=c.onErrorMax}else c.isValid=
!0}},compareValid:function(d){var a=d.setting,c=e("#"+d.id),f=e("#"+a.desID),d=a.dataType;curvalue=c.val();ls_data=f.val();if(d=="number")if(!isNaN(curvalue)&&!isNaN(ls_data))curvalue=parseFloat(curvalue),ls_data=parseFloat(ls_data);else return;if(d=="date"||d=="datetime")if(c=!1,d=="date"&&(c=isDate(curvalue)&&isDate(ls_data)),d=="datetime"&&(c=isDateTime(curvalue)&&isDateTime(ls_data)),c)curvalue=new Date(curvalue),ls_data=new Date(ls_data);else return;switch(a.operateor){case "=":a.isValid=curvalue==
ls_data;break;case "!=":a.isValid=curvalue!=ls_data;break;case ">":a.isValid=curvalue>ls_data;break;case ">=":a.isValid=curvalue>=ls_data;break;case "<":a.isValid=curvalue<ls_data;break;case "<=":a.isValid=curvalue<=ls_data;break;default:a.isValid=!1}},passwordValid:function(d){function a(a){for(var a=a.toLowerCase(),e=0,c=0;c<a.length;c++)if(a.charCodeAt(c)!=e+1&&e!=0)return!1;else e=a.charCodeAt(c);return!0}function c(a){for(var a=a.toLowerCase(),e=0,c=0;c<a.length;c++)if(a.charCodeAt(c)!=e&&e!=
0)return!1;else e=a.charCodeAt(c);return!0}function f(a,e,c){e==void 0&&(e=[0,0,0,0]);c==void 0&&(c=-1);c++;e[c]=a%2;a=Math.floor(a/2);if(a==1||a==0)return e[c+1]=a,e;return e=f(a,e,c)}var g=d.settings[d.validatorPasswordIndex],d=d.value;if(d=="")return 0;if(g.onErrorContinueChar!=""&&a(d))return-1;if(g.onErrorSameChar!=""&&c(d))return-2;if(g.compareID!=""&&e("#"+g.compareID).val()==d)return-3;for(var h=[0,0,0,0],i=d.length,g=0;g<i;g++){var j=d.charCodeAt(g);j>=48&&j<=57?h[0]+=1:j>=97&&j<=122?h[1]+=
1:j>=65&&j<=90?h[2]+=1:"!,@,#,$,%,^,&,*,?,_,~".indexOf(d.substr(g,1))>=0&&(h[3]+=1)}var l=0,m=!0;e.each(passwordStrengthRule,function(a,c){var d=c.level;e.each(c.rule,function(a,c){var g=0;m=!0;e.each(f(c.flag),function(a,e){if(e==1){var d=c.value[g++],d=d==0?i:d>i?i:d;if(h[a]<d)return m=!1}});if(m)return l=d,!1});m&&(l=d)});return l},localTooltip:function(d){var d=d||window.event,a=d.pageX||(d.clientX?d.clientX+document.body.scrollLeft:0),d=d.pageY||(d.clientY?d.clientY+document.body.scrollTop:0);
e("#fvtt").css({top:d+2+"px",left:a-40+"px"})},reloadAutoTip:function(d){d==void 0&&(d="1");var a=e.formValidator.getInitConfig(d);e.each(a.validObjects,function(){if(a.mode=="AutoTip"){var c=this.settings[0],d="#"+c.relativeID,g=e(d).offset(),h=g.top,d=e(d).width()+g.left;e("#"+c.tipID).parent().show().css({left:d+"px",top:h+"px"})}})},getStatusText:function(d,a){return e.isFunction(a)?a(e(d).val()):a},resetInputValue:function(d,a,c){(c?e("#"+c):e(a.showTextObjects)).each(function(a,c){if(c.isInputControl){var e=
c.settings[0].onShowText;if(d&&e==c.value)c.value="";if(!d&&e!=""&&c.value=="")c.value=e}})}};e.fn.formValidator=function(d){var d=d||{},a={};if(d.validatorGroup==void 0)d.validatorGroup="1";e.extend(!0,a,formValidator_setting);var c=e.formValidator.getInitConfig(d.validatorGroup);c.validCount+=1;if(c.mode=="SingleTip")a.tipCss={left:10,top:1,width:22,height:22,display:"none"};if(c.mode=="AlertTip")a.autoModify=!0;e.extend(!0,a,d||{});return this.each(function(){this.validatorIndex=c.validCount-1;
this.validatorGroup=d.validatorGroup;var f=e(this),g={};e.extend(!0,g,a);var h=f.attr("id");h||(h=Math.ceil(Math.random()*5E7),f.attr("id",h));var i=g.tipID?g.tipID:h+"Tip";if(c.mode=="AutoTip"||c.mode=="FixTip"){var j=e("#"+i);if(c.mode=="AutoTip"&&j.length==0){var j=e("<div style='position:absolute;' id='"+i+"'></div>"),l=g.relativeID?g.relativeID:h,m=e("#"+l).offset();g.tipCss.top=m.top+g.tipCss.top;g.tipCss.left=e("#"+l).width()+m.left+g.tipCss.left;e("<div style='position:absolute;' id='"+i+
"'></div>").appendTo(e("body")).css(g.tipCss);a.relativeID=l}j.css("margin","0px").css("padding","0px").css("background","transparent")}else c.mode=="SingleTip"&&f.showTooltips();a.tipID=i;a.pwdTipID=g.pwdTipID?g.pwdTipID:a.tipID;a.fixTipID=g.fixTipID?g.fixTipID:h+"FixTip";e.formValidator.appendValid(h,a);j=e.inArray(f,c.validObjects);if(j==-1){if(g.ajax)g=c.ajaxObjects,c.ajaxObjects=g+(g!=""?",#":"#")+h;c.validObjects.push(this)}else c.validObjects[j]=this;c.mode!="AlertTip"&&e.formValidator.setTipState(this,
"onShow",a.onShow);var g=this.tagName.toLowerCase(),j=this.type,l=a.defaultValue,k=j=="password"||j=="text"||j=="textarea";this.isInputControl=k;l&&f.val(l);var p=e("#"+a.fixTipID),n=a.onShowFixText;p.length==1&&onMouseOutFixTextHtml!=""&&onMouseOnFixTextHtml!=""&&n!=""&&(f.hover(function(){p.html(onMouseOnFixTextHtml.replace(/\$data\$/g,n))},function(){p.html(onMouseOutFixTextHtml.replace(/\$data\$/g,n))}),p.css("padding","0px 0px 0px 0px").css("margin","0px 0px 0px 0px").html(onMouseOutFixTextHtml.replace(/\$data\$/g,
a.onShowFixText)));var o=a.onShowText;if(g=="input"||g=="textarea"){if(k&&o!="")showObjs=c.showTextObjects,c.showTextObjects=showObjs+(showObjs!=""?",#":"#")+h,f.val(o),f.css("color",a.onShowTextColor.mouseOutColor);f.focus(function(){if(k){var d=f.val();this.validValueOld=d;if(o==d)this.value="",f.css("color",a.onShowTextColor.mouseOnColor)}if(c.mode!="AlertTip")d=e("#"+i),this.lastshowclass=d.attr("class"),this.lastshowmsg=d.text(),e.formValidator.setTipState(this,"onFocus",a.onFocus);this.validatorPasswordIndex>
0&&(e("#"+a.pwdTipID).show(),f.trigger("keyup"))});f.bind("keyup",function(){if(this.validatorPasswordIndex>0)try{var c=e.formValidator.oneIsValid(h),d=e.formValidator.passwordValid(this);d<0&&(d=0);c.isValid||(d=0);e("#"+a.pwdTipID).show();e("#"+a.pwdTipID).html(passwordStrengthStatusHtml[d])}catch(f){alert("\u5bc6\u7801\u5f3a\u5ea6\u6821\u9a8c\u5931\u8d25,\u9519\u8bef\u539f\u56e0:\u53d8\u91cfpasswordStrengthStatusHtml\u8bed\u6cd5\u9519\u8bef\u6216\u8005\u4e3a\u8bbe\u7f6e)")}});f.bind(a.triggerEvent,
function(){var d=this.settings;if(d[0].leftTrim)this.value=this.replace(/^\s*/g,"");if(d[0].rightTrim)this.value=this.replace(/\s*$/g,"");if(k){if(this.value==""&&o!="")this.value=o;this.value==o&&f.css("color",a.onShowTextColor.mouseOutColor)}d=e.formValidator.oneIsValid(h);if(d!=null)if(d.ajax>=0)e.formValidator.showAjaxMessage(d);else{var g=e.formValidator.showMessage(d);if(!d.isValid)if(a.autoModify&&k)e(this).val(this.validValueOld),c.mode!="AlertTip"&&e.formValidator.setTipState(this,"onShow",
e.formValidator.getStatusText(this,a.onCorrect));else if(c.forceValid||a.forceValid)alert(g),this.focus()}})}else g=="select"&&f.bind({focus:function(){c.mode!="AlertTip"&&e.formValidator.setTipState(this,"onFocus",a.onFocus)},blur:function(){(this.validValueOld==void 0||this.validValueOld==f.val())&&e(this).trigger("change")},change:function(){var a=e.formValidator.oneIsValid(h);a!=null&&(a.ajax>=0?e.formValidator.showAjaxMessage(a):e.formValidator.showMessage(a))}})})};e.fn.inputValidator=function(d){var a=
{};e.extend(!0,a,inputValidator_setting,d||{});return this.each(function(){e.formValidator.appendValid(this.id,a)})};e.fn.compareValidator=function(d){var a={};e.extend(!0,a,compareValidator_setting,d||{});return this.each(function(){e.formValidator.appendValid(this.id,a)})};e.fn.regexValidator=function(d){var a={};e.extend(!0,a,regexValidator_setting,d||{});return this.each(function(){e.formValidator.appendValid(this.id,a)})};e.fn.functionValidator=function(d){var a={};e.extend(!0,a,functionValidator_setting,
d||{});return this.each(function(){e.formValidator.appendValid(this.id,a)})};e.fn.ajaxValidator=function(d){var a={};e.extend(!0,a,ajaxValidator_setting,d||{});return this.each(function(){var c=e.formValidator.getInitConfig(this.validatorGroup),d=c.ajaxObjects;if((d+",").indexOf("#"+this.id+",")==-1)c.ajaxObjects=d+(d!=""?",#":"#")+this.id;this.validatorAjaxIndex=e.formValidator.appendValid(this.id,a)})};e.fn.passwordValidator=function(d){var a={};e.extend(!0,a,passwordValidator_setting,d||{});return this.each(function(){this.validatorPasswordIndex=
e.formValidator.appendValid(this.id,a)})};e.fn.defaultPassed=function(d){return this.each(function(){var a=this.settings;this.onceValided=a[0].defaultPassed=!0;for(var c=1;c<a.length;c++)a[c].isValid=!0,!e.formValidator.getInitConfig(a[0].validatorGroup).mode=="AlertTip"&&e.formValidator.setTipState(this,d?"onShow":"onCorrect",a[0].onCorrect)})};e.fn.unFormValidator=function(d){return this.each(function(){if(this.settings)this.settings[0].bind=!d,d?e("#"+this.settings[0].tipID).hide():e("#"+this.settings[0].tipID).show()})};
e.fn.showTooltips=function(){e("body [id=fvtt]").length==0&&(fvtt=e("<div id='fvtt' style='position:absolute;z-index:56002'></div>"),e("body").append(fvtt),fvtt.before("<iframe index=0 src='about:blank' class='fv_iframe' scrolling='no' frameborder='0'></iframe>"));return this.each(function(){jqobj=e(this);s=e("<span class='top' id=fv_content style='display:block'></span>");b=e("<b class='bottom' style='display:block' />");this.tooltip=e("<span class='fv_tooltip' style='display:block'></span>").append(s).append(b).css({filter:"alpha(opacity:95)",
KHTMLOpacity:"0.95",MozOpacity:"0.95",opacity:"0.95"});jqobj.bind({mouseover:function(d){e("#fvtt").empty().append(this.tooltip).show();e("#fv_content").html(this.Tooltip);e.formValidator.localTooltip(d)},mouseout:function(){e("#fvtt").hide()},mousemove:function(d){e.formValidator.localTooltip(d)}})})}})(jQuery);
var initConfig_setting={theme:"Default",validatorGroup:"1",formID:"",submitOnce:!0,ajaxForm:null,mode:"FixTip",errorFocus:!0,wideWord:!1,forceValid:!1,debug:!1,inIframe:!1,onSuccess:function(){return!0},onError:$.noop,status:"",ajaxPrompt:"\u5f53\u524d\u6709\u6570\u636e\u6b63\u5728\u8fdb\u884c\u670d\u52a1\u5668\u7aef\u6821\u9a8c\uff0c\u8bf7\u7a0d\u5019",validCount:0,ajaxCountSubmit:0,ajaxCountValid:0,validObjects:[],ajaxObjects:"",showTextObjects:"",validateType:"initConfig"},formValidator_setting=
{validatorGroup:"1",onShowText:"",onShowTextColor:{mouseOnColor:"#000000",mouseOutColor:"#999999"},onShowFixText:"",onShow:"",onFocus:"",onCorrect:"",onEmpty:"",empty:!1,autoModify:!1,defaultValue:null,bind:!0,ajax:!1,validateType:"formValidator",tipCss:{left:10,top:-4,height:20,width:280},triggerEvent:"blur",forceValid:!1,tipID:null,pwdTipID:null,fixTipID:null,relativeID:null,index:0,leftTrim:!1,rightTrim:!1},inputValidator_setting={isValid:!1,type:"size",min:0,max:99999,onError:"\u8f93\u5165\u9519\u8bef",
validateType:"inputValidator",empty:{leftEmpty:!0,rightEmpty:!0,leftEmptyError:null,rightEmptyError:null}},compareValidator_setting={isValid:!1,desID:"",operateor:"=",onError:"\u8f93\u5165\u9519\u8bef",validateType:"compareValidator"},regexValidator_setting={isValid:!1,regExp:"",param:"i",dataType:"string",compareType:"||",onError:"\u8f93\u5165\u7684\u683c\u5f0f\u4e0d\u6b63\u786e",validateType:"regexValidator"},ajaxForm_setting={type:"GET",url:window.location.href,dataType:"html",timeout:1E5,data:null,
async:!0,cache:!1,buttons:null,beforeSend:function(){return!0},success:function(){return!0},complete:$.noop,processData:!0,error:$.noop},ajaxValidator_setting={isValid:!1,lastValid:"",oneceValid:!1,randNumberName:"rand",onError:"\u670d\u52a1\u5668\u6821\u9a8c\u6ca1\u6709\u901a\u8fc7",onWait:"\u6b63\u5728\u7b49\u5f85\u670d\u52a1\u5668\u8fd4\u56de\u6570\u636e",validateType:"ajaxValidator"};$.extend(!0,ajaxValidator_setting,ajaxForm_setting);
var functionValidator_setting={isValid:!0,fun:function(){this.isValid=!0},validateType:"functionValidator",onError:"\u8f93\u5165\u9519\u8bef"},passwordValidator_setting={isValid:!0,compareID:"",validateType:"passwordValidator",onErrorContinueChar:"\u5bc6\u7801\u5b57\u7b26\u4e3a\u8fde\u7eed\u5b57\u7b26\u4e0d\u88ab\u5141\u8bb8",onErrorSameChar:"\u5bc6\u7801\u5b57\u7b26\u90fd\u76f8\u540c\u4e0d\u88ab\u5141\u8bb8",onErrorCompareSame:"\u5bc6\u7801\u4e8e\u7528\u6237\u540d\u76f8\u540c\u4e0d\u88ab\u5141\u8bb8"},
validatorGroup_setting=[],fv_scriptSrc=document.getElementsByTagName("script")[document.getElementsByTagName("script").length-1].src;
